@TCViettelFC_API_HostAddress = https://localhost:5000
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiIxIiwiUm9sZUlkIjoiMiIsIm5iZiI6MTcyNzYwMDA2NSwiZXhwIjoxNzI3NjIxNjY1LCJpYXQiOjE3Mjc2MDAwNjUsImlzcyI6IkZBMjRfU0VQNDkwX0c1MyIsImF1ZCI6IkZBMjRfU0VQNDkwX0c1MyJ9.q7R_Xrj5LrMgG8TnpvcrqVo4sYTAM19V_0RcWgH5OyU
GET {{TCViettelFC_API_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{TCViettelFC_API_HostAddress}}/api/User/getbyuser/
Authorization: Bearer {{Token}}
###
###
POST {{TCViettelFC_API_HostAddress}}/api/Admin/changepass
Authorization: Bearer {{Token}}
Content-Type: application/x-www-form-urlencoded

newpass=1235
